/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monitoringbilling;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Jhon Kenneth Doroja
 */
public class addshipment extends javax.swing.JFrame {

        Connection cn=null;
        PreparedStatement ps=null;
        ResultSet rs=null;
        
    public addshipment() {
        initComponents();
        jTextField8_add.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2_add = new javax.swing.JTextField();
        jTextField3_add = new javax.swing.JTextField();
        jTextField4_add = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField1_add = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField8_add = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextField10_add = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextField5_add = new javax.swing.JTextArea();
        jTextField6_add = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField7_add = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jTextField9_add = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextField11_add = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField12_add = new datechooser.beans.DateChooserCombo();
        jTextField13_add = new datechooser.beans.DateChooserCombo();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));

        jLabel1.setFont(new java.awt.Font("Centaur", 1, 30)); // NOI18N
        jLabel1.setText("ADD TRANSACTION");

        jLabel2.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel2.setText("CUSTOMERS FIRSTNAME");

        jLabel3.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel3.setText("CUSTOMERS MIDDLENAME");

        jLabel4.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel4.setText("CUSTOMERS LASTNAME");

        jLabel5.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel5.setText("CUSTOMERS MOBILE NO.");

        jTextField2_add.setFont(new java.awt.Font("Century", 0, 16)); // NOI18N
        jTextField2_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2_addActionPerformed(evt);
            }
        });
        jTextField2_add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2_addKeyPressed(evt);
            }
        });

        jTextField3_add.setFont(new java.awt.Font("Century", 0, 16)); // NOI18N
        jTextField3_add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3_addKeyPressed(evt);
            }
        });

        jTextField4_add.setFont(new java.awt.Font("Century", 0, 16)); // NOI18N
        jTextField4_add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4_addKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel7.setText("CUSTOMERS ADDRESS");

        jLabel13.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel13.setText("TRANSACTION NO:");

        jTextField1_add.setFont(new java.awt.Font("Century", 0, 16)); // NOI18N
        jTextField1_add.setAutoscrolls(false);
        jTextField1_add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1_addKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1_addKeyReleased(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel14.setText("PAYMENT COSTS:");

        jTextField8_add.setFont(new java.awt.Font("Century", 0, 16)); // NOI18N
        jTextField8_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8_addActionPerformed(evt);
            }
        });
        jTextField8_add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField8_addKeyTyped(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Century", 1, 16)); // NOI18N
        jLabel15.setText("PHP");

        jLabel17.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel17.setText("COMPANY NAME NAME");

        jPanel3.setBackground(new java.awt.Color(255, 153, 0));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel19.setFont(new java.awt.Font("Century", 1, 16)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancel (1).png"))); // NOI18N
        jLabel19.setText("CANCEL");
        jLabel19.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 153, 0));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel18.setFont(new java.awt.Font("Century", 1, 16)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save (2).png"))); // NOI18N
        jLabel18.setText("INSERT");
        jLabel18.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Century", 1, 16)); // NOI18N
        jLabel6.setText("(+639)");

        jTextField10_add.setColumns(20);
        jTextField10_add.setFont(new java.awt.Font("Century", 0, 16)); // NOI18N
        jTextField10_add.setRows(5);
        jTextField10_add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField10_addKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTextField10_add);

        jTextField5_add.setColumns(20);
        jTextField5_add.setFont(new java.awt.Font("Century", 0, 16)); // NOI18N
        jTextField5_add.setRows(5);
        jTextField5_add.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jTextField5_addAncestorMoved(evt);
            }
        });
        jTextField5_add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5_addKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTextField5_add);

        jTextField6_add.setFont(new java.awt.Font("Century", 1, 16)); // NOI18N
        jTextField6_add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField6_addKeyPressed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel20.setText("TRANSACTION TYPE");

        jTextField7_add.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jTextField7_add.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "SIZE 20", "SIZE 40" }));
        jTextField7_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7_addActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel21.setText("COMPANY ADDRESS");

        jTextField9_add.setFont(new java.awt.Font("Century", 0, 16)); // NOI18N
        jTextField9_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9_addActionPerformed(evt);
            }
        });
        jTextField9_add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField9_addKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField9_addKeyTyped(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel22.setText("COMPANY CONTACT NO.");

        jTextField11_add.setFont(new java.awt.Font("Century", 0, 16)); // NOI18N
        jTextField11_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11_addActionPerformed(evt);
            }
        });
        jTextField11_add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField11_addKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField11_addKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField11_addKeyTyped(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel23.setText("DATE PAYED");

        jLabel24.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel24.setText("DATE OF PAYMENT");

        jTextField13_add.setCurrentView(new datechooser.view.appearance.AppearancesList("Swing",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    try {
        jTextField13_add.setDefaultPeriods(new datechooser.model.multiple.PeriodSet());
    } catch (datechooser.model.exeptions.IncompatibleDataExeption e1) {
        e1.printStackTrace();
    }
    jTextField13_add.setEnabled(false);

    jLabel8.setFont(new java.awt.Font("Century", 1, 16)); // NOI18N
    jLabel8.setText("(+639)");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel16)
                    .addGap(0, 0, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel13)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(517, 517, 517))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField9_add, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel23)
                            .addGap(252, 252, 252)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField13_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField12_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(95, 95, 95)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField11_add, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField8_add)
                                        .addComponent(jScrollPane1)))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel20)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel6))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel15))
                                .addComponent(jLabel17)
                                .addComponent(jLabel21)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel22)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel8))
                                .addComponent(jLabel24))
                            .addGap(55, 55, 55)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField7_add, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField2_add, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextField6_add)
                                        .addComponent(jTextField3_add)
                                        .addComponent(jTextField1_add)
                                        .addComponent(jTextField4_add)
                                        .addComponent(jScrollPane2))
                                    .addGap(6, 6, 6)))))))
            .addGap(29, 29, 29))
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(66, 66, 66)
            .addComponent(jLabel1)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel16)
            .addGap(29, 29, 29)
            .addComponent(jLabel1)
            .addGap(47, 47, 47)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel13)
                .addComponent(jTextField1_add, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(15, 15, 15)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTextField2_add, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel2))
            .addGap(15, 15, 15)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTextField3_add, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel3))
            .addGap(15, 15, 15)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTextField4_add, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel4))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel5)
                        .addComponent(jTextField6_add, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(jTextField7_add, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField8_add, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)
                        .addComponent(jLabel15))
                    .addGap(9, 9, 9)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField9_add, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(jLabel7)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel21)
                    .addGap(35, 35, 35)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTextField11_add, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel22)
                .addComponent(jLabel8))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addComponent(jLabel24))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField13_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField12_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel23))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGap(65, 75, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        frame = new JFrame("Please Confirm.");
        if (JOptionPane.showConfirmDialog(frame, "Please Confirm your Container Number, Once you've save it. it cannot be change again.", "Please Confirm.", JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION){
            frame = new JFrame("Confirmed?");
            if (JOptionPane.showConfirmDialog(frame, "Have you already confirmed your container no? Are you Sure?", "Confirmed?", JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION){

                try{
                    String sql = "INSERT INTO `shipments` (Con_No, Consignee_FirstName, Consignee_MiddleName, Consignee_LastName, Consignee_Address, Consignee_Mobile_No, Container_Type, Deposit_Costs, Shipping_Line_Name, Shipping_Line_Address, Shipping_Line_Contact_No, Date_of_Deposit, Date_of_Refund) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)";

                    cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/monitoring","root","");
                    ps=cn.prepareStatement(sql);

                    ps.setString(1, jTextField1_add.getText());
                    ps.setString(2, jTextField2_add.getText());
                    ps.setString(3, jTextField3_add.getText());
                    ps.setString(4, jTextField4_add.getText());
                    ps.setString(5, jTextField5_add.getText());
                    ps.setString(6, jTextField6_add.getText());
                    String value = jTextField7_add.getSelectedItem().toString();
                    ps.setString(7, value);
                    ps.setString(8, jTextField8_add.getText());
                    ps.setString(9, jTextField10_add.getText());
                    ps.setString(10, jTextField9_add.getText());
                    ps.setString(11, jTextField11_add.getText());
                    ps.setString(12, jTextField12_add.getText());
                    ps.setString(13, jTextField13_add.getText());

                    ps.executeUpdate();
                    if (jTextField1_add.getText().trim().isEmpty()) {
                        JOptionPane.showMessageDialog(null, "Please Input a Container No");
                    }else if(jTextField2_add.getText().trim().isEmpty()){
                        JOptionPane.showMessageDialog(null, "Please Input a Consignee's FirstName");
                    }else if(jTextField3_add.getText().trim().isEmpty()){
                        JOptionPane.showMessageDialog(null, "Please Input a Consignee's MiddleName");
                    }else if(jTextField4_add.getText().trim().isEmpty()){
                        JOptionPane.showMessageDialog(null, "Please Input a Consignee's LastName");
                    }else if(jTextField5_add.getText().trim().isEmpty()){
                        JOptionPane.showMessageDialog(null, "Please Input a Consignee's Address");
                    }else if(jTextField6_add.getText().trim().isEmpty()){
                        JOptionPane.showMessageDialog(null, "Please Input a Consignee's Mobile No");
                    }else if(jTextField7_add.getSelectedItem().toString().equals("")){
                        JOptionPane.showMessageDialog(null, "Please Choose a Container Type");
                    }else if(jTextField8_add.getText().trim().isEmpty()){
                        JOptionPane.showMessageDialog(null, "Please Input a Deposit Costs");
                    }else if(jTextField10_add.getText().trim().isEmpty()){
                        JOptionPane.showMessageDialog(null, "Please Input a Shipping Line");
                    }else if(jTextField10_add.getText().trim().isEmpty()){
                        JOptionPane.showMessageDialog(null, "Please Input a Shipping Line Address");
                    }else if(jTextField10_add.getText().trim().isEmpty()){
                        JOptionPane.showMessageDialog(null, "Please Input a Shipping Line Contact No.");
                    }else if(jTextField10_add.getText().trim().isEmpty()){
                        JOptionPane.showMessageDialog(null, "Please Input a Date of Deposit");
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Shipment Created Succesfully");

                        new viewshipments().setVisible(true);
                        this.dispose();

                    }
                }catch (Exception e)
                {
                    JOptionPane.showMessageDialog(null, e);
                }
                new addshipment().setVisible(false);
            }
        }

        /*Monitoring a=new Monitoring();
        a.Inserts();
        dispose();*/
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        frame = new JFrame("Cancel.");
        if (JOptionPane.showConfirmDialog(frame, "Please Confirm if you want to Cancel.", "Cancel", JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION){
            this.dispose();
            new viewshipments().setVisible(true);
        }
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jTextField8_addKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8_addKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField8_addKeyTyped

    private void jTextField1_addKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1_addKeyReleased
        int position = jTextField1_add.getCaretPosition();
        jTextField1_add.setText(jTextField1_add.getText().toUpperCase());
        jTextField1_add.setCaretPosition(position);
    }//GEN-LAST:event_jTextField1_addKeyReleased

    private void jTextField1_addKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1_addKeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c)||Character.isISOControl(c)||Character.isDigit(c)){
            jTextField1_add.setEditable(true);
        }else{
            jTextField1_add.setEditable(false);
        }
    }//GEN-LAST:event_jTextField1_addKeyPressed

    private void jTextField4_addKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4_addKeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)){
            jTextField4_add.setEditable(true);
        }else{
            jTextField4_add.setEditable(false);
        }
    }//GEN-LAST:event_jTextField4_addKeyPressed

    private void jTextField3_addKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3_addKeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)){
            jTextField3_add.setEditable(true);
        }else{
            jTextField3_add.setEditable(false);
        }
    }//GEN-LAST:event_jTextField3_addKeyPressed

    private void jTextField2_addKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2_addKeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)){
            jTextField2_add.setEditable(true);
        }else{
            jTextField2_add.setEditable(false);
        }
    }//GEN-LAST:event_jTextField2_addKeyPressed

    private void jTextField2_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2_addActionPerformed

    private void jTextField10_addKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField10_addKeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)||Character.isDigit(c)){
            jTextField10_add.setEditable(true);
        }else{
            jTextField10_add.setEditable(false);
        }
    }//GEN-LAST:event_jTextField10_addKeyPressed

    private void jTextField5_addKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5_addKeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)||Character.isDigit(c)){
            jTextField5_add.setEditable(true);
        }else{
            jTextField5_add.setEditable(false);
        }
    }//GEN-LAST:event_jTextField5_addKeyPressed

    private void jTextField8_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8_addActionPerformed

    private void jTextField5_addAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextField5_addAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5_addAncestorMoved

    private void jTextField6_addKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6_addKeyPressed
    String phonenumber = jTextField6_add.getText();
    
    int length= phonenumber.length();
    
    char c = evt.getKeyChar();
    
    if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
        if (length<9){
            jTextField6_add.setEditable(true);
        }else{
            jTextField6_add.setEditable(false);
        }
        
    }else{
        if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
            jTextField6_add.setEditable(true);
        }else{
            jTextField6_add.setEditable(false);
        }
    }
    }//GEN-LAST:event_jTextField6_addKeyPressed

    private void jTextField9_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9_addActionPerformed

    private void jTextField9_addKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9_addKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9_addKeyTyped

    private void jTextField11_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11_addActionPerformed

    private void jTextField11_addKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField11_addKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11_addKeyTyped

    private void jTextField7_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7_addActionPerformed
        if(jTextField7_add.getSelectedItem().toString().equals("SIZE 20")){
            jTextField8_add.setText("7000");
        }else if(jTextField7_add.getSelectedItem().toString().equals("SIZE 40")){
            jTextField8_add.setText("14000");
        }else{
            jTextField8_add.setText("");
        }
    }//GEN-LAST:event_jTextField7_addActionPerformed

    private void jTextField11_addKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField11_addKeyReleased

    }//GEN-LAST:event_jTextField11_addKeyReleased

    private void jTextField9_addKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9_addKeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)){
            jTextField9_add.setEditable(true);
        }else{
            jTextField9_add.setEditable(false);
        }
    }//GEN-LAST:event_jTextField9_addKeyPressed

    private void jTextField11_addKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField11_addKeyPressed
    String phonenumber = jTextField11_add.getText();
    
    int length= phonenumber.length();
    
    char c = evt.getKeyChar();
    
    if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
        if (length<9){
            jTextField11_add.setEditable(true);
        }else{
            jTextField11_add.setEditable(false);
        }
        
    }else{
        if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
            jTextField11_add.setEditable(true);
        }else{
            jTextField11_add.setEditable(false);
        }
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11_addKeyPressed
private JFrame frame;


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addshipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addshipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addshipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addshipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addshipment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTextArea jTextField10_add;
    public static javax.swing.JTextField jTextField11_add;
    private datechooser.beans.DateChooserCombo jTextField12_add;
    private datechooser.beans.DateChooserCombo jTextField13_add;
    public static javax.swing.JTextField jTextField1_add;
    public static javax.swing.JTextField jTextField2_add;
    public static javax.swing.JTextField jTextField3_add;
    public static javax.swing.JTextField jTextField4_add;
    public static javax.swing.JTextArea jTextField5_add;
    public static javax.swing.JTextField jTextField6_add;
    private javax.swing.JComboBox<String> jTextField7_add;
    public static javax.swing.JTextField jTextField8_add;
    public static javax.swing.JTextField jTextField9_add;
    // End of variables declaration//GEN-END:variables
}
