/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monitoringbilling;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import static monitoringbilling.Select.jTextArea1_select;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

public class viewshipments extends javax.swing.JFrame {

        Connection cn=null;
        PreparedStatement ps=null;
        ResultSet rs=null;
        
    public viewshipments() {
        initComponents();
        showtable();
        jTextField1_view.setEditable(false);
        jTextField8_view.setEditable(false);
        jTextField12_view.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        insertpanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        updatepanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        confirmpanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        selectpanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1_view = new javax.swing.JLabel();
        jLabel2_view = new javax.swing.JLabel();
        jLabel3_view = new javax.swing.JLabel();
        jLabel4_view = new javax.swing.JLabel();
        jLabel5_view = new javax.swing.JLabel();
        jTextField1_view = new javax.swing.JTextField();
        jTextField2_view = new javax.swing.JTextField();
        jTextField3_view = new javax.swing.JTextField();
        jTextField4_view = new javax.swing.JTextField();
        jTextField5_view = new javax.swing.JTextField();
        jLabel6_view = new javax.swing.JLabel();
        jTextField6_view = new javax.swing.JTextField();
        jLabel8_view = new javax.swing.JLabel();
        jTextField8_view = new javax.swing.JTextField();
        jLabel9_view = new javax.swing.JLabel();
        jTextField9_view = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10_view = new javax.swing.JLabel();
        jLabel11_view = new javax.swing.JLabel();
        jLabel7_view = new javax.swing.JLabel();
        jTextField10_view = new javax.swing.JTextField();
        jTextField11_view = new javax.swing.JTextField();
        jLabel12_view = new javax.swing.JLabel();
        jLabel13_view = new javax.swing.JLabel();
        jTextField7_view = new javax.swing.JComboBox<>();
        jTextField13_view = new datechooser.beans.DateChooserCombo();
        filter = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField12_view = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("TRANSACTIONS");

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel5.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close.png"))); // NOI18N
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/minimize.png"))); // NOI18N
        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/left-arrow.png"))); // NOI18N
        jLabel19.setToolTipText("");
        jLabel19.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel6)
                .addGap(0, 0, 0)
                .addComponent(jLabel5))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        insertpanel.setBackground(new java.awt.Color(255, 153, 51));
        insertpanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel3.setFont(new java.awt.Font("Century", 1, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add-button1.png"))); // NOI18N
        jLabel3.setText("CREATE TRANSACTION");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout insertpanelLayout = new javax.swing.GroupLayout(insertpanel);
        insertpanel.setLayout(insertpanelLayout);
        insertpanelLayout.setHorizontalGroup(
            insertpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        insertpanelLayout.setVerticalGroup(
            insertpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        updatepanel.setBackground(new java.awt.Color(255, 153, 51));
        updatepanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel8.setFont(new java.awt.Font("Century", 1, 16)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/update.png"))); // NOI18N
        jLabel8.setText("UPDATE TRANSACTION");
        jLabel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout updatepanelLayout = new javax.swing.GroupLayout(updatepanel);
        updatepanel.setLayout(updatepanelLayout);
        updatepanelLayout.setHorizontalGroup(
            updatepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        updatepanelLayout.setVerticalGroup(
            updatepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        confirmpanel.setBackground(new java.awt.Color(255, 153, 51));
        confirmpanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel4.setFont(new java.awt.Font("Century", 1, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save1.png"))); // NOI18N
        jLabel4.setText("CONFIRM TRANSACTION");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout confirmpanelLayout = new javax.swing.GroupLayout(confirmpanel);
        confirmpanel.setLayout(confirmpanelLayout);
        confirmpanelLayout.setHorizontalGroup(
            confirmpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        confirmpanelLayout.setVerticalGroup(
            confirmpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane2.setDoubleBuffered(true);
        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        selectpanel.setBackground(new java.awt.Color(255, 153, 51));
        selectpanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel9.setFont(new java.awt.Font("Century", 1, 16)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/select.png"))); // NOI18N
        jLabel9.setText("READ TRANSACTION");
        jLabel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jLabel9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel9KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout selectpanelLayout = new javax.swing.GroupLayout(selectpanel);
        selectpanel.setLayout(selectpanelLayout);
        selectpanelLayout.setHorizontalGroup(
            selectpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        selectpanelLayout.setVerticalGroup(
            selectpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel1_view.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1_view.setText("CONTAINER NO");

        jLabel2_view.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2_view.setText("CONSIGNEE FIRSTNAME");

        jLabel3_view.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3_view.setText("CONSIGNEE MIDDLENAME");

        jLabel4_view.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4_view.setText("CONSIGNEE LASTNAME");

        jLabel5_view.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5_view.setText("CONSIGNEE ADDRESS");

        jTextField1_view.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        jTextField2_view.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jTextField2_view.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2_viewKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2_viewKeyTyped(evt);
            }
        });

        jTextField3_view.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jTextField3_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3_viewActionPerformed(evt);
            }
        });
        jTextField3_view.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3_viewKeyPressed(evt);
            }
        });

        jTextField4_view.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jTextField4_view.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4_viewKeyPressed(evt);
            }
        });

        jTextField5_view.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jTextField5_view.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5_viewKeyPressed(evt);
            }
        });

        jLabel6_view.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6_view.setText("CONSIGNEE MOBILE NO.");

        jTextField6_view.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jTextField6_view.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField6_viewKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField6_viewKeyTyped(evt);
            }
        });

        jLabel8_view.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8_view.setText("DEPOSIT COSTS (PHP)");

        jTextField8_view.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jTextField8_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8_viewActionPerformed(evt);
            }
        });
        jTextField8_view.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField8_viewKeyTyped(evt);
            }
        });

        jLabel9_view.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9_view.setText("SHIPPING LINE NAME");

        jTextField9_view.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jTextField9_view.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField9_viewKeyPressed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/refresh2.png"))); // NOI18N
        jButton1.setText("Refresh            ");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/history2.png"))); // NOI18N
        jButton2.setText("TRANSACTION History");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel10_view.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10_view.setText("SHIPPING LINE ADDRESS");

        jLabel11_view.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11_view.setText("SHIPPING LINE CONTACT NO.");

        jLabel7_view.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7_view.setText("CONTAINER TYPE");

        jTextField10_view.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jTextField10_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10_viewActionPerformed(evt);
            }
        });
        jTextField10_view.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField10_viewKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField10_viewKeyTyped(evt);
            }
        });

        jTextField11_view.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jTextField11_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11_viewActionPerformed(evt);
            }
        });
        jTextField11_view.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField11_viewKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField11_viewKeyTyped(evt);
            }
        });

        jLabel12_view.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12_view.setText("DATE OF DEPOSIT");

        jLabel13_view.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13_view.setText("DATE OF REFUND");

        jTextField7_view.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jTextField7_view.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "SIZE 20", "SIZE 40" }));
        jTextField7_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7_viewActionPerformed(evt);
            }
        });

        filter.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterActionPerformed(evt);
            }
        });
        filter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                filterKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filterKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                filterKeyTyped(evt);
            }
        });

        jLabel7.setText("Search");

        jTextField12_view.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jTextField12_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12_viewActionPerformed(evt);
            }
        });
        jTextField12_view.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField12_viewKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField12_viewKeyTyped(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/confirmation.png"))); // NOI18N
        jButton3.setText("Print");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1_view)
                            .addComponent(jTextField1_view, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(315, 315, 315)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2_view, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2_view)
                            .addComponent(jTextField3_view, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3_view)
                            .addComponent(jTextField4_view, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4_view)
                            .addComponent(jLabel5_view)
                            .addComponent(jTextField5_view, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6_view, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6_view))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(filter, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11_view)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 866, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(confirmpanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(updatepanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(insertpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton2))
                                            .addComponent(selectpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10_view)
                            .addComponent(jTextField10_view, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7_view)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField7_view, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8_view))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12_view)
                                    .addComponent(jTextField11_view, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField8_view, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9_view))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13_view)
                                    .addComponent(jTextField12_view, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField9_view, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField13_view, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(filter, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(2, 2, 2)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton2)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1_view)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1_view, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2_view)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2_view, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3_view)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3_view, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4_view)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField4_view, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5_view)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField5_view, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6_view)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField6_view, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7_view)
                            .addComponent(jLabel11_view))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField7_view, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField11_view, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(insertpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8_view)
                                    .addComponent(jLabel12_view))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField8_view, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField12_view, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9_view)
                                    .addComponent(jLabel13_view))
                                .addGap(2, 2, 2)
                                .addComponent(jTextField9_view, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(selectpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(updatepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(confirmpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jTextField13_view, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10_view)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField10_view, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
private JFrame frame;
    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to Exit", "Exit", JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }

    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        this.setExtendedState(viewshipments.ICONIFIED);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        new homepage().setVisible(true);
        new viewshipments().setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.dispose();
        new addshipment().setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        frame = new JFrame("Update");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to Update", "Update", JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION){

            if (jTextField1_view.getText().trim().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Insert Container No.");
            }
            else if (jTextField2_view.getText().trim().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Insert Consignee FirstName.");
            }
            else if (jTextField3_view.getText().trim().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Insert Consignee MiddleName.");
            }
            else if (jTextField4_view.getText().trim().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Insert Consignee LastName.");
            }
            else if (jTextField5_view.getText().trim().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Insert Consignee Address.");
            }
            else if (jTextField6_view.getText().trim().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Insert Consignee Mobile No.");
            }
            else if (jTextField7_view.getSelectedItem().toString().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Insert Container Type.");
            }
            else if (jTextField8_view.getText().trim().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Insert Deposit Costs.");
            }
            else if (jTextField9_view.getText().trim().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Insert Shipping Line Name.");
            }
            else if (jTextField10_view.getText().trim().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Insert Shipping Line Address.");
            }
            else if (jTextField11_view.getText().trim().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Insert Shipping Line Contact No.");
            }
            else if (jTextField12_view.getText().trim().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Insert Date of Deposit.");
            }
            else if (jTextField13_view.getText().trim().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Insert Date of Refund.");
            }

            else
            {

                try
                {
                    String sql = "UPDATE shipments SET Con_No=?, Consignee_FirstName=?,"
                               + " Consignee_MiddleName=?, Consignee_LastName=?, Consignee_Address=?, Consignee_Mobile_No=?, Container_Type=?, Deposit_Costs=?,"
                               + " Shipping_Line_Name=?, Shipping_Line_Address=?, Shipping_Line_Contact_No=?, Date_of_Deposit=?, Date_of_Refund=? WHERE Con_No=?";

                    cn = DriverManager.getConnection("jdbc:mysql://localhost/monitoring","root","");
                    ps = cn.prepareStatement(sql);

                    ps.setString(14, jTextField1_view.getText());
                    ps.setString(1, jTextField1_view.getText());
                    ps.setString(2, jTextField2_view.getText());
                    ps.setString(3, jTextField3_view.getText());
                    ps.setString(4, jTextField4_view.getText());
                    ps.setString(5, jTextField5_view.getText());
                    ps.setString(6, jTextField6_view.getText());
                    String value = jTextField7_view.getSelectedItem().toString();
                    ps.setString(7, value);
                    ps.setString(8, jTextField8_view.getText());
                    ps.setString(9, jTextField9_view.getText());
                    ps.setString(10, jTextField10_view.getText());
                    ps.setString(11, jTextField11_view.getText());
                    ps.setString(12, jTextField12_view.getText());
                    ps.setString(13, jTextField13_view.getText());

                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Shipment Updated Succesfully.");

                    this.dispose();
                    new viewshipments().setVisible(true);
                    this.dispose();

                }
                catch (HeadlessException | SQLException ex)
                {
                    JOptionPane.showMessageDialog(null, ex);
                }
            }
            showtable();
            
        }

        /*frame = new JFrame("Update");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to Update", "Update", JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION){Monitoring a = new Monitoring();
            a.updateships();
            frame.validate();
        }*/
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        int x = JOptionPane.showConfirmDialog(null, "Are you sure?","Confirm?",JOptionPane.YES_NO_OPTION);
        if(x==0){
            if (jTextField1_view.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please Input a Container No");
            }else if(jTextField2_view.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(null, "Please Input a Consignee FirstName");
            }else if(jTextField3_view.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(null, "Please Input a Consignee MiddleName");
            }else if(jTextField4_view.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(null, "Please Input a Consignee LastName");
            }else if(jTextField5_view.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(null, "Please Input a Consignee Address");
            }else if(jTextField6_view.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(null, "Please Input a Consignee Mobile No");
            }else if(jTextField7_view.getSelectedItem().toString().equals("")){
                JOptionPane.showMessageDialog(null, "Please Input a Container Type");
            }else if(jTextField8_view.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(null, "Please Input a Deposit Costs");
            }else if(jTextField9_view.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(null, "Please Input a Shipping Line Name");
            }else if(jTextField10_view.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(null, "Please Input a Shipping Line Address");
            }else if(jTextField11_view.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(null, "Please Input a Shipping Line Contact No");
            }else if(jTextField12_view.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(null, "Please Input a Date of Deposit");
            }else if(jTextField13_view.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(null, "Please Input a Date of Refund");
            }
            else{
                try{
                    String sql="INSERT INTO history(Con_No, Consignee_FirstName, Consignee_MiddleName, Consignee_LastName, Consignee_Address, Consignee_Mobile_No, Container_Type, Deposit_Costs,"
                              +"Shipping_Line_Name, Shipping_Line_Address, Shipping_Line_Contact_No, Date_of_Deposit, Date_of_Refund)"
                    + "VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)";
                    cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/monitoring","root","");
                    ps=cn.prepareStatement(sql);

                    ps.setString(1, jTextField1_view.getText());
                    ps.setString(2, jTextField2_view.getText());
                    ps.setString(3, jTextField3_view.getText());
                    ps.setString(4, jTextField4_view.getText());
                    ps.setString(5, jTextField5_view.getText());
                    ps.setString(6, jTextField6_view.getText());
                    String value = jTextField7_view.getSelectedItem().toString();
                    ps.setString(7, value);
                    ps.setString(8, jTextField8_view.getText());
                    ps.setString(9, jTextField9_view.getText());
                    ps.setString(10, jTextField10_view.getText());
                    ps.setString(11, jTextField11_view.getText());
                    ps.setString(12, jTextField12_view.getText());
                    ps.setString(13, jTextField13_view.getText());
                    
                    ps.executeUpdate();

                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                try {
                    String sql= "DELETE FROM `shipments` WHERE Con_No=?";
                    cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/monitoring","root","");
                    ps=cn.prepareStatement(sql);

                    ps.setString(1, jTextField1_view.getText());
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Shipment Confirmed");
                    new viewshipments().setVisible(true);
                    this.dispose();

                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }

            }
        }else{
            JOptionPane.showMessageDialog(null,"Shipment Confirmation Canceled");
        }
        showtable();

        /*Monitoring a = new Monitoring();
        a.confirmships();*/

    }//GEN-LAST:event_jLabel4MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
boolean a = jTable1.isEditing();
if (a==false){
   
        int i = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        jTextField1_view.setText(model.getValueAt(i,0).toString());
        jTextField2_view.setText(model.getValueAt(i,1).toString());
        jTextField3_view.setText(model.getValueAt(i,2).toString());
        jTextField4_view.setText(model.getValueAt(i,3).toString());
        jTextField5_view.setText(model.getValueAt(i,4).toString());
        jTextField6_view.setText(model.getValueAt(i,5).toString());
        jTextField7_view.setSelectedItem(model.getValueAt(i,6).toString());
        jTextField8_view.setText(model.getValueAt(i,7).toString());
        jTextField9_view.setText(model.getValueAt(i,8).toString());
        jTextField10_view.setText(model.getValueAt(i,9).toString());
        jTextField11_view.setText(model.getValueAt(i,10).toString());
        jTextField12_view.setText(model.getValueAt(i,11).toString());
        jTextField13_view.setText(model.getValueAt(i,12).toString());
        JOptionPane.showMessageDialog(null,"Row Selected");
}
    }//GEN-LAST:event_jTable1MouseClicked

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked

    }//GEN-LAST:event_jScrollPane2MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked

        try {
            String sql="select * from shipments where Con_No=?";
            cn = DriverManager.getConnection("jdbc:mysql://localhost/monitoring","root","");
            ps = cn.prepareStatement(sql);
            ps.setString(1,jTextField1_view.getText());

            rs=ps.executeQuery();
            if (rs.next()) {

                new Select().setVisible(true);
                jTextArea1_select.setText("\tGT LORENZO LOGISTICS INC\n\n"
                    + "Room 303, AVR Building, Beaterio Street, Intramuros\n"
                    + "Manila, Philippines\n\n"
                    + "Shipment Records:\n"
                    + "_______________________________________________________________________________________________________\n"
                    + "| Field Names\t\t|\t Field Values \t\t\t                  |\n"
                    + "_______________________________________________________________________________________________________\n\n"
                    + "\n"+jLabel1_view.getText()+":\t\t|\t"+jTextField1_view.getText()+"\n\n"
                    + ""+jLabel2_view.getText()+":\t\t|\t"+jTextField2_view.getText()+"\n\n"
                    + ""+jLabel3_view.getText()+":\t|\t"+jTextField3_view.getText()+"\n\n"
                    + ""+jLabel4_view.getText()+":\t\t|\t"+jTextField4_view.getText()+"\n\n"
                    + ""+jLabel5_view.getText()+":\t\t|\t"+jTextField5_view.getText()+"\n\n"
                    + ""+jLabel6_view.getText()+":\t\t|\t"+jTextField6_view.getText()+"\n\n"
                    + ""+jLabel7_view.getText()+":\t\t|\t"+jTextField7_view.getSelectedItem()+"\n\n"
                    + ""+jLabel8_view.getText()+":\t\t|\t"+jTextField8_view.getText()+"\n\n"
                    + ""+jLabel9_view.getText()+":\t\t|\t"+jTextField9_view.getText()+"\n\n"
                    + ""+jLabel10_view.getText()+":\t|\t"+jTextField10_view.getText()+"\n\n"    
                    + ""+jLabel11_view.getText()+":\t|\t"+jTextField11_view.getText()+"\n\n"
                    + ""+jLabel12_view.getText()+":\t\t|\t"+jTextField12_view.getText()+"\n\n"  
                    + ""+jLabel13_view.getText()+":\t\t|\t"+jTextField13_view.getText()+"\n\n"            
                    + "_______________________________________________________________________________________________________\n\n\n\n"
                    + "\t\t\t   Gerald T. Lorenzo\n"
                    + "\t\t\t_____________________\n"
                    + "\t\t\tCOMPANY DIRECTOR");

            } else {
                JOptionPane.showMessageDialog(null, "There is no Value given.");

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        /*Monitoring a = new Monitoring();
        a.view();*/
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel9KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9KeyPressed

    private void jTextField3_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3_viewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3_viewActionPerformed

    private void jTextField6_viewKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6_viewKeyTyped
 
    }//GEN-LAST:event_jTextField6_viewKeyTyped

    private void jTextField8_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8_viewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8_viewActionPerformed

    private void jTextField8_viewKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8_viewKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE)){
            evt.consume();
        }                // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8_viewKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new viewshipments().setVisible(true);
        this.dispose();
        showtable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Refundhistory().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2_viewKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2_viewKeyTyped

    }//GEN-LAST:event_jTextField2_viewKeyTyped

    private void jTextField2_viewKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2_viewKeyPressed
        char c = evt.getKeyChar();
    if (Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)){
        jTextField2_view.setEditable(true);
    }else{
        jTextField2_view.setEditable(false);
    }
    }//GEN-LAST:event_jTextField2_viewKeyPressed

    private void jTextField3_viewKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3_viewKeyPressed
        char c = evt.getKeyChar();
    if (Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)){
        jTextField3_view.setEditable(true);
    }else{
        jTextField3_view.setEditable(false);
    }
    }//GEN-LAST:event_jTextField3_viewKeyPressed

    private void jTextField4_viewKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4_viewKeyPressed
        char c = evt.getKeyChar();
    if (Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)){
        jTextField4_view.setEditable(true);
    }else{
        jTextField4_view.setEditable(false);
    }
    }//GEN-LAST:event_jTextField4_viewKeyPressed

    private void jTextField5_viewKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5_viewKeyPressed
        char c = evt.getKeyChar();
    if (Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)||Character.isDigit(c)){
        jTextField5_view.setEditable(true);
    }else{
        jTextField5_view.setEditable(false);
    }
    }//GEN-LAST:event_jTextField5_viewKeyPressed

    private void jTextField9_viewKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9_viewKeyPressed
        char c = evt.getKeyChar();
    if (Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)){
        jTextField9_view.setEditable(true);
    }else{
        jTextField9_view.setEditable(false);
    }
    }//GEN-LAST:event_jTextField9_viewKeyPressed

    private void jTextField6_viewKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6_viewKeyPressed
        String phonenumber = jTextField6_view.getText();
    
    int length= phonenumber.length();
    
    char c = evt.getKeyChar();
    
    if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
        if (length<9){
            jTextField6_view.setEditable(true);
        }else{
            jTextField6_view.setEditable(false);
        }
        
    }else{
        if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
            jTextField6_view.setEditable(true);
        }else{
            jTextField6_view.setEditable(false);
        }
    }
    }//GEN-LAST:event_jTextField6_viewKeyPressed

    private void jTextField10_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10_viewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10_viewActionPerformed

    private void jTextField10_viewKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField10_viewKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10_viewKeyTyped

    private void jTextField11_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11_viewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11_viewActionPerformed

    private void jTextField11_viewKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField11_viewKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11_viewKeyTyped

    private void jTextField11_viewKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField11_viewKeyPressed
        String phonenumber = jTextField11_view.getText();
    
    int length= phonenumber.length();
    
    char c = evt.getKeyChar();
    
    if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
        if (length<9){
            jTextField11_view.setEditable(true);
        }else{
            jTextField11_view.setEditable(false);
        }
        
    }else{
        if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
            jTextField11_view.setEditable(true);
        }else{
            jTextField11_view.setEditable(false);
        }
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11_viewKeyPressed

    private void jTextField10_viewKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField10_viewKeyPressed
        char c = evt.getKeyChar();
    if (Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)||Character.isDigit(c)){
        jTextField10_view.setEditable(true);
    }else{
        jTextField10_view.setEditable(false);
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10_viewKeyPressed

    private void filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filterActionPerformed

    private void filterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filterKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_filterKeyPressed

    private void filterKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filterKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_filterKeyTyped

    private void filterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filterKeyReleased
        DefaultTableModel table = (DefaultTableModel)jTable1.getModel();
        String search = filter.getText().toLowerCase().toUpperCase();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
        jTable1.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_filterKeyReleased

    private void jTextField7_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7_viewActionPerformed
        if(jTextField7_view.getSelectedItem().toString().equals("SIZE 20")){
            jTextField8_view.setText("7000");
        }else if(jTextField7_view.getSelectedItem().toString().equals("SIZE 40")){
            jTextField8_view.setText("1400/0");
        }else{
            jTextField8_view.setText("");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7_viewActionPerformed

    private void jTextField12_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12_viewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12_viewActionPerformed

    private void jTextField12_viewKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField12_viewKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12_viewKeyPressed

    private void jTextField12_viewKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField12_viewKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12_viewKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
        Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/monitoring","root","");
        InputStream in = new FileInputStream(new File("C:\\Users\\Jhon Kenneth Doroja\\Documents\\NetBeansProjects\\MonitoringBilling\\src\\monitoringbilling\\dorojabobo.jrxml"));
        JasperDesign jd =JRXmlLoader.load(in);
        HashMap para = new HashMap();
        JasperReport jr = JasperCompileManager.compileReport(jd);
        JasperPrint jp = JasperFillManager.fillReport(jr, para,cn);
        JasperViewer.viewReport(jp, false);
        
        }catch(Exception e){
         JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    public void showtable(){
    try{
        cn =DriverManager.getConnection("jdbc:mysql://localhost/monitoring", "root", "");
        String sql = "SELECT * FROM shipments";
        ps = cn.prepareStatement(sql);
        rs = ps.executeQuery();
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        
        
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewshipments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewshipments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewshipments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewshipments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewshipments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel confirmpanel;
    public static javax.swing.JTextField filter;
    private javax.swing.JPanel insertpanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel10_view;
    public static javax.swing.JLabel jLabel11_view;
    public static javax.swing.JLabel jLabel12_view;
    public static javax.swing.JLabel jLabel13_view;
    private javax.swing.JLabel jLabel19;
    public static javax.swing.JLabel jLabel1_view;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel2_view;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel3_view;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel4_view;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel5_view;
    private javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel6_view;
    private javax.swing.JLabel jLabel7;
    public static javax.swing.JLabel jLabel7_view;
    private javax.swing.JLabel jLabel8;
    public static javax.swing.JLabel jLabel8_view;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JLabel jLabel9_view;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    public static javax.swing.JTextField jTextField10_view;
    public static javax.swing.JTextField jTextField11_view;
    public static javax.swing.JTextField jTextField12_view;
    private datechooser.beans.DateChooserCombo jTextField13_view;
    public static javax.swing.JTextField jTextField1_view;
    public static javax.swing.JTextField jTextField2_view;
    public static javax.swing.JTextField jTextField3_view;
    public static javax.swing.JTextField jTextField4_view;
    public static javax.swing.JTextField jTextField5_view;
    public static javax.swing.JTextField jTextField6_view;
    private javax.swing.JComboBox<String> jTextField7_view;
    public static javax.swing.JTextField jTextField8_view;
    public static javax.swing.JTextField jTextField9_view;
    private javax.swing.JPanel selectpanel;
    private javax.swing.JPanel updatepanel;
    // End of variables declaration//GEN-END:variables
}
